language: python
python: '3.6'
env:
  global:
  - FRONTEND_PATH=$TRAVIS_BUILD_DIR
  - DOCKER_PATH=$TRAVIS_BUILD_DIR/docker/release/Dockerfile
  - IMAGE_TAG=planimation/frontend:latest
services:
- docker
jobs:
  include:
  - stage: Build docker image
    script:
    - docker build -t $IMAGE_TAG --build-arg LICENSE_FILE=Unity_v2018.x.ulf -f $DOCKER_PATH
      $FRONTEND_PATH
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push $IMAGE_TAG
before_install:
- openssl aes-256-cbc -K $encrypted_ab4d680825db_key -iv $encrypted_ab4d680825db_iv
  -in Unity_v2018.x.ulf.enc -out ./Unity_v2018.x.ulf -d
